language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck
   
before_install:
 - chmod +x gradlew
