language: android
android:
        components:
                - platform-tools
                - build-tools-23.0.1
                - android-23
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
